import {
  Body,
  Controller,
  Get,
  Param,
  Patch,
  Post,
  Req,
  Res,
  UnauthorizedException,
} from '@nestjs/common';
import { Throttle } from '@nestjs/throttler';
import { z } from 'zod';
import type { Request, Response } from 'express';
import {
  acceptInvitationSchema,
  changeAccountPasswordSchema,
  loginSchema,
  passwordSchema,
  setupOwnerSchema,
  updateAccountProfileSchema,
  updateAccountPreferencesSchema,
  verifyTwoFactorLoginSchema,
} from '@coda/contracts';
import { env } from '../config/env';
import { RealtimeGateway } from '../realtime/realtime.gateway';
import { AuthService } from './auth.service';
import { assertPasswordDoesNotContainEmail } from './password-policy';
import { Public } from './public.decorator';
import { SetupTokenService } from './setup-token.service';
import { TwoFactorService } from './two-factor.service';

@Controller('api/v1')
export class AuthController {
  constructor(
    private readonly auth: AuthService,
    private readonly realtime: RealtimeGateway,
    private readonly setupToken: SetupTokenService,
    private readonly twoFactor: TwoFactorService,
  ) {}

  @Public()
  @Get('setup/status')
  @Throttle({ default: { limit: 30, ttl: 60_000 } })
  async status() {
    const status = await this.auth.setupStatus();
    return {
      data: {
        ...status,
        setupTokenRequired: this.setupToken.required,
        setupTokenAutoGenerated: this.setupToken.autoGenerated,
      },
    };
  }

  @Public()
  @Post('setup/owner')
  @Throttle({ default: { limit: 5, ttl: 600_000 } })
  async setup(
    @Req() request: Request,
    @Body() body: unknown,
    @Res({ passthrough: true }) response: Response,
  ) {
    if (this.setupToken.required) {
      const provided = request.header('x-coda-setup-token') ?? '';
      if (!this.setupToken.verify(provided)) {
        throw new UnauthorizedException('The instance setup token is invalid');
      }
    }
    const input = setupOwnerSchema.parse(body);
    assertPasswordDoesNotContainEmail(input.password, input.email);
    const user = await this.auth.setupOwner(input);
    this.setupToken.markInitialized();
    await this.setSession(request, response, user.id);
    return { data: { id: user.id, email: user.email, displayName: user.displayName } };
  }

  @Public()
  @Post('auth/login')
  @Throttle({ default: { limit: 5, ttl: 60_000 } })
  async login(
    @Req() request: Request,
    @Body() body: unknown,
    @Res({ passthrough: true }) response: Response,
  ) {
    const input = loginSchema.parse(body);
    // Password verification (with its timing-equalized dummy hash and lockout) runs
    // identically for every account and throws the same 401 on failure. The second
    // factor is only ever revealed after this call returns a user, so a 2FA account
    // is indistinguishable from a non-2FA one until the password is correct.
    const user = await this.auth.login(input.email, input.password);
    if (await this.twoFactor.hasActiveTwoFactor(user.id)) {
      const challenge = await this.twoFactor.createChallenge(user.id);
      return { data: { twoFactorRequired: true as const, challenge } };
    }
    await this.setSession(request, response, user.id);
    return { data: { id: user.id, email: user.email, displayName: user.displayName } };
  }

  @Public()
  @Post('auth/login/2fa')
  @Throttle({ default: { limit: 10, ttl: 60_000 } })
  async verifyTwoFactorLogin(
    @Req() request: Request,
    @Body() body: unknown,
    @Res({ passthrough: true }) response: Response,
  ) {
    const input = verifyTwoFactorLoginSchema.parse(body);
    const userId = await this.twoFactor.verifyLogin(input.challenge, input.code);
    const user = await this.auth.userIdentity(userId);
    await this.setSession(request, response, user.id);
    return { data: { id: user.id, email: user.email, displayName: user.displayName } };
  }

  @Post('auth/logout')
  async logout(@Req() request: Request, @Res({ passthrough: true }) response: Response) {
    await this.auth.logout(request.sessionId);
    if (request.sessionId) await this.realtime.disconnectSession(request.sessionId);
    response.clearCookie(env().SESSION_COOKIE_NAME, { path: '/' });
    response.clearCookie('coda_csrf', { path: '/' });
    return { data: { loggedOut: true } };
  }

  @Get('auth/session')
  session(@Req() request: Request) {
    return { data: request.user };
  }

  @Get('account')
  async account(@Req() request: Request) {
    return { data: await this.auth.account(request.user!.id) };
  }

  @Patch('account/profile')
  async updateAccountProfile(@Req() request: Request, @Body() body: unknown) {
    return {
      data: await this.auth.updateAccountProfile(
        request.user!.id,
        updateAccountProfileSchema.parse(body),
      ),
    };
  }

  @Patch('account/preferences')
  async updateAccountPreferences(@Req() request: Request, @Body() body: unknown) {
    return {
      data: await this.auth.updateAccountPreferences(
        request.user!.id,
        updateAccountPreferencesSchema.parse(body),
      ),
    };
  }

  @Post('account/password')
  @Throttle({ default: { limit: 5, ttl: 60_000 } })
  async changeAccountPassword(@Req() request: Request, @Body() body: unknown) {
    const input = changeAccountPasswordSchema.parse(body);
    return {
      data: await this.auth.changeAccountPassword(
        request.user!.id,
        request.sessionId,
        input.currentPassword,
        input.newPassword,
      ),
    };
  }

  @Public()
  @Get('invitations/:token')
  @Throttle({ default: { limit: 30, ttl: 60_000 } })
  async invitation(@Param('token') token: string) {
    return { data: await this.auth.invitation(token) };
  }

  @Public()
  @Post('invitations/accept')
  @Throttle({ default: { limit: 10, ttl: 60_000 } })
  async accept(
    @Req() request: Request,
    @Body() body: unknown,
    @Res({ passthrough: true }) response: Response,
  ) {
    const input = acceptInvitationSchema.parse(body);
    const invitation = await this.auth.invitation(input.token);
    const invitedEmail = invitation.email ?? input.email;
    if (input.password && invitedEmail) {
      assertPasswordDoesNotContainEmail(input.password, invitedEmail);
    }
    const user = await this.auth.acceptInvitation(input, request.user?.id);
    if (invitation.project) {
      await this.realtime.invalidateProject(invitation.project.id, 'memberships', []);
    }
    if (!request.user) await this.setSession(request, response, user.id);
    return { data: { id: user.id, email: user.email, displayName: user.displayName } };
  }

  @Post('users/:userId/reset-links')
  @Throttle({ default: { limit: 10, ttl: 60_000 } })
  async resetLink(@Req() request: Request, @Param('userId') userId: string) {
    const { reset, token } = await this.auth.createResetLink(request.user!.id, userId);
    return {
      data: {
        id: reset.id,
        expiresAt: reset.expiresAt,
        resetUrl: `/reset-password?token=${encodeURIComponent(token)}`,
      },
    };
  }

  @Public()
  @Post('auth/reset-password')
  @Throttle({ default: { limit: 5, ttl: 60_000 } })
  async resetPassword(@Body() body: unknown) {
    const input = z.object({ token: z.string().min(32), password: passwordSchema }).parse(body);
    return { data: await this.auth.resetPassword(input.token, input.password) };
  }

  private async setSession(request: Request, response: Response, userId: string): Promise<void> {
    const { token, csrf, session } = await this.auth.createSession(
      userId,
      request.get?.('user-agent'),
    );
    const secure = new URL(env().APP_ORIGIN).protocol === 'https:';
    response.cookie(env().SESSION_COOKIE_NAME, token, {
      httpOnly: true,
      sameSite: 'lax',
      secure,
      expires: session.expiresAt,
      path: '/',
    });
    response.cookie('coda_csrf', csrf, {
      httpOnly: false,
      sameSite: 'lax',
      secure,
      expires: session.expiresAt,
      path: '/',
    });
  }
}
