import { Logger } from '@nestjs/common';
import { beforeEach, describe, expect, it, vi } from 'vitest';

// Production + uninitialized would normally generate and announce a boot token; the desktop preset
// must suppress the entire ceremony regardless, because it auto-initializes a local owner instead.
vi.mock('../config/env', () => ({
  env: () => ({ NODE_ENV: 'production', SETUP_TOKEN: undefined }),
}));
vi.mock('../config/runtime-capabilities', () => ({
  runtimeCapabilities: () => ({ setupTokenBootstrap: 'local-owner' }),
}));

import { SetupTokenService } from './setup-token.service';

describe('SetupTokenService under the desktop profile', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  it('never generates, announces, or requires a setup token', async () => {
    const warn = vi.spyOn(Logger.prototype, 'warn').mockImplementation(() => undefined);
    const prisma = { instanceSettings: { count: vi.fn().mockResolvedValue(0) } };
    const service = new SetupTokenService(prisma as never);

    await service.bootstrap();

    // The instance is never even inspected, and no banner is printed.
    expect(prisma.instanceSettings.count).not.toHaveBeenCalled();
    expect(warn).not.toHaveBeenCalled();
    expect(service.required).toBe(false);
    expect(service.autoGenerated).toBe(false);
    expect(service.verify('anything-at-all-1234567890')).toBe(false);
  });
});
