import { Logger } from '@nestjs/common';
import { beforeEach, describe, expect, it, vi } from 'vitest';

const envState: { NODE_ENV: 'development' | 'test' | 'production'; SETUP_TOKEN?: string } = {
  NODE_ENV: 'production',
  SETUP_TOKEN: undefined,
};

vi.mock('../config/env', () => ({ env: () => envState }));

import { SetupTokenService } from './setup-token.service';

function prismaWith(count: number) {
  return { instanceSettings: { count: vi.fn().mockResolvedValue(count) } };
}

function bannerToken(warn: { mock: { calls: unknown[][] } }): string {
  const line = warn.mock.calls
    .map((call: unknown[]) => String(call[0]))
    .find((entry: string) => entry.includes('CODA SETUP TOKEN'));
  expect(line).toBeDefined();
  return /CODA SETUP TOKEN: (\S+)/u.exec(line!)![1]!;
}

describe('SetupTokenService', () => {
  beforeEach(() => {
    envState.NODE_ENV = 'production';
    envState.SETUP_TOKEN = undefined;
    vi.restoreAllMocks();
  });

  it('generates, announces, and verifies a token when production and uninitialized', async () => {
    const warn = vi.spyOn(Logger.prototype, 'warn').mockImplementation(() => undefined);
    const service = new SetupTokenService(prismaWith(0) as never);

    await service.bootstrap();

    expect(service.required).toBe(true);
    expect(service.autoGenerated).toBe(true);
    const token = bannerToken(warn);
    expect(token.length).toBeGreaterThanOrEqual(32);
    expect(service.verify(token)).toBe(true);
    expect(service.verify(`${token}tampered`)).toBe(false);
    expect(service.verify('an-entirely-different-value-1234')).toBe(false);
  });

  it('never generates when an explicit token is configured and defers to it', async () => {
    envState.SETUP_TOKEN = 'x'.repeat(40);
    const warn = vi.spyOn(Logger.prototype, 'warn').mockImplementation(() => undefined);
    const prisma = prismaWith(0);
    const service = new SetupTokenService(prisma as never);

    await service.bootstrap();

    expect(prisma.instanceSettings.count).not.toHaveBeenCalled();
    expect(warn).not.toHaveBeenCalled();
    expect(service.required).toBe(true);
    expect(service.autoGenerated).toBe(false);
    expect(service.verify('x'.repeat(40))).toBe(true);
    expect(service.verify('y'.repeat(40))).toBe(false);
  });

  it('does not generate or require a token outside production', async () => {
    envState.NODE_ENV = 'development';
    const warn = vi.spyOn(Logger.prototype, 'warn').mockImplementation(() => undefined);
    const service = new SetupTokenService(prismaWith(0) as never);

    await service.bootstrap();

    expect(warn).not.toHaveBeenCalled();
    expect(service.required).toBe(false);
    expect(service.autoGenerated).toBe(false);
    expect(service.verify('anything')).toBe(false);
  });

  it('never generates or announces once the instance is initialized', async () => {
    const warn = vi.spyOn(Logger.prototype, 'warn').mockImplementation(() => undefined);
    const service = new SetupTokenService(prismaWith(1) as never);

    await service.bootstrap();

    expect(warn).not.toHaveBeenCalled();
    expect(service.required).toBe(false);
    expect(service.verify('anything')).toBe(false);
  });

  it('retires a generated token after initialization so it is no longer accepted', async () => {
    const warn = vi.spyOn(Logger.prototype, 'warn').mockImplementation(() => undefined);
    const service = new SetupTokenService(prismaWith(0) as never);
    await service.bootstrap();
    const token = bannerToken(warn);
    expect(service.verify(token)).toBe(true);

    service.markInitialized();

    expect(service.required).toBe(false);
    expect(service.autoGenerated).toBe(false);
    expect(service.verify(token)).toBe(false);
  });
});
