import { Injectable, Logger } from '@nestjs/common';
import { timingSafeEqual } from 'node:crypto';
import { createToken, hashToken } from '../common/crypto';
import { env } from '../config/env';
import { runtimeCapabilities } from '../config/runtime-capabilities';
import { PrismaService } from '../prisma/prisma.service';

const GENERATED_TOKEN_BYTES = 32;
const BANNER_RULE = '='.repeat(72);

/**
 * Owns the instance setup token used to authorize first-run owner creation.
 *
 * An explicit `SETUP_TOKEN` always takes precedence. When it is absent in a
 * production deployment that has not been initialized yet, a high-entropy token
 * is generated at boot, only its hash is retained in memory, and the value is
 * printed once per boot inside an unmissable log banner so the operator can copy
 * it from the container logs. Nothing is generated, printed, or accepted once the
 * instance has an owner.
 */
@Injectable()
export class SetupTokenService {
  private readonly logger = new Logger(SetupTokenService.name);
  private generatedTokenHash: string | null = null;

  constructor(private readonly prisma: PrismaService) {}

  /**
   * Generates and announces a boot token when required. Safe to call once during
   * bootstrap; a no-op when an explicit token is set, outside production, or when
   * the instance is already initialized.
   */
  async bootstrap(): Promise<void> {
    // The token ceremony is a server-profile capability; the desktop preset auto-initializes a
    // local owner instead (see LocalOwnerBootstrap) and never issues or accepts a setup token.
    if (runtimeCapabilities().setupTokenBootstrap !== 'token-ceremony') return;
    if (env().SETUP_TOKEN) return;
    if (env().NODE_ENV !== 'production') return;
    if ((await this.prisma.instanceSettings.count()) > 0) return;
    const token = createToken(GENERATED_TOKEN_BYTES);
    this.generatedTokenHash = hashToken(token);
    this.emitBanner(token);
  }

  /** Whether the setup endpoint expects a token (explicit or auto-generated). */
  get required(): boolean {
    return Boolean(env().SETUP_TOKEN) || this.generatedTokenHash !== null;
  }

  /** Whether the active token was auto-generated rather than operator-provided. */
  get autoGenerated(): boolean {
    return !env().SETUP_TOKEN && this.generatedTokenHash !== null;
  }

  /** Constant-time comparison of a presented token against the active token. */
  verify(provided: string): boolean {
    const explicitToken = env().SETUP_TOKEN;
    const expectedHash = explicitToken ? hashToken(explicitToken) : this.generatedTokenHash;
    if (!expectedHash) return false;
    return timingSafeEqual(
      Buffer.from(hashToken(provided), 'hex'),
      Buffer.from(expectedHash, 'hex'),
    );
  }

  /** Retires any generated token so it is never accepted after initialization. */
  markInitialized(): void {
    this.generatedTokenHash = null;
  }

  private emitBanner(token: string): void {
    this.logger.warn(BANNER_RULE);
    this.logger.warn(`======== CODA SETUP TOKEN: ${token} ========`);
    this.logger.warn('Enter this token on the setup screen to create the owner account.');
    this.logger.warn(
      'It appears only in these logs, is regenerated on every restart until setup completes, and stops working afterward.',
    );
    this.logger.warn(BANNER_RULE);
  }
}
