import { expect, test, type BrowserContext, type Page } from '@playwright/test';

import { createScreenplayViaApi, storageStatePath } from './support/harness';

const editorContent = '.cm-content[contenteditable="true"]';
const e2eOrigin = process.env.CODA_E2E_URL ?? 'http://localhost:3000';

async function typeAtDocumentEnd(page: Page, text: string): Promise<void> {
  await page.locator(editorContent).click();
  await page.keyboard.press('ControlOrMeta+End');
  await page.keyboard.press('Enter');
  await page.keyboard.insertText(text);
}

async function typeAtDocumentStart(page: Page, text: string): Promise<void> {
  await page.locator(editorContent).click();
  await page.keyboard.press('ControlOrMeta+Home');
  await page.keyboard.insertText(text);
  await page.keyboard.press('Enter');
}

async function expectEditorText(page: Page, text: string): Promise<void> {
  await expect.poll(() => page.locator(editorContent).innerText()).toContain(text);
}

async function routeInitializedSetup(target: BrowserContext | Page): Promise<void> {
  await target.route('**/api/v1/setup/status', (route) =>
    route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        data: {
          initialized: true,
          setupTokenRequired: true,
          setupTokenAutoGenerated: false,
        },
      }),
    }),
  );
}

test('offline edits replay on reconnect and undo stays scoped to the invoking client', async ({
  browser,
  page,
}) => {
  const screenplayId = await createScreenplayViaApi(page, {
    title: `Collaboration recovery ${Date.now()}`,
    sourceText: 'FADE IN:\n',
  });
  const peerContext = await browser.newContext({
    baseURL: e2eOrigin,
    storageState: storageStatePath,
  });
  const peer = await peerContext.newPage();
  try {
    await Promise.all([routeInitializedSetup(page), routeInitializedSetup(peerContext)]);
    await Promise.all([
      page.goto(`/screenplays/${screenplayId}`),
      peer.goto(`/screenplays/${screenplayId}`),
    ]);
    await Promise.all([expectEditorText(page, 'FADE IN:'), expectEditorText(peer, 'FADE IN:')]);
    await expect(page.getByText('CONNECTION READY')).toBeVisible();
    await expect(peer.getByText('CONNECTION READY')).toBeVisible();

    await page.context().setOffline(true);
    await expect(page.getByText('CONNECTION OFFLINE')).toBeVisible();
    await typeAtDocumentEnd(page, 'ALICE OFFLINE');
    await typeAtDocumentStart(peer, 'BOB ONLINE');
    await expectEditorText(peer, 'BOB ONLINE');
    await expect(peer.locator(editorContent)).not.toContainText('ALICE OFFLINE');

    await page.context().setOffline(false);
    await expect(page.getByText('CONNECTION READY')).toBeVisible();
    await Promise.all([
      expectEditorText(page, 'ALICE OFFLINE'),
      expectEditorText(page, 'BOB ONLINE'),
      expectEditorText(peer, 'ALICE OFFLINE'),
      expectEditorText(peer, 'BOB ONLINE'),
    ]);

    // Keep this local edit in a separate UndoManager capture window from the offline draft above.
    await page.waitForTimeout(600);
    await typeAtDocumentEnd(page, 'ALICE UNDO');
    await expectEditorText(peer, 'ALICE UNDO');
    await typeAtDocumentStart(peer, 'BOB SURVIVES');
    await expectEditorText(page, 'BOB SURVIVES');

    await page.locator(editorContent).click();
    await page.keyboard.press('ControlOrMeta+z');

    await expect(page.locator(editorContent)).not.toContainText('ALICE UNDO');
    await expect(peer.locator(editorContent)).not.toContainText('ALICE UNDO');
    await Promise.all([
      expectEditorText(page, 'ALICE OFFLINE'),
      expectEditorText(page, 'BOB SURVIVES'),
      expectEditorText(peer, 'ALICE OFFLINE'),
      expectEditorText(peer, 'BOB SURVIVES'),
    ]);

    await expect
      .poll(async () => {
        const response = await page.request.get(`/api/v1/screenplays/${screenplayId}`);
        const body = (await response.json()) as { data: { sourceText: string } };
        return body.data.sourceText;
      })
      .toContain('BOB SURVIVES');
  } finally {
    await page.context().setOffline(false);
    await peerContext.close();
  }
});

test('comment anchors survive a concurrent insert and stay out of Fountain export', async ({
  browser,
  page,
}) => {
  const sourceText = 'FADE IN:\n\nINT. ROOM - DAY\n\nAction.\n';
  const screenplayId = await createScreenplayViaApi(page, {
    title: `Anchored comments ${Date.now()}`,
    sourceText,
  });
  const peerContext = await browser.newContext({
    baseURL: e2eOrigin,
    storageState: storageStatePath,
  });
  const peer = await peerContext.newPage();
  try {
    await Promise.all([routeInitializedSetup(page), routeInitializedSetup(peerContext)]);
    await Promise.all([
      page.goto(`/screenplays/${screenplayId}`),
      peer.goto(`/screenplays/${screenplayId}`),
    ]);
    await Promise.all([expectEditorText(page, 'FADE IN:'), expectEditorText(peer, 'FADE IN:')]);
    await page.locator(editorContent).click();
    await page.keyboard.press('ControlOrMeta+Home');
    for (let index = 0; index < 'FADE IN:'.length; index += 1) {
      await page.keyboard.press('Shift+ArrowRight');
    }

    await page.getByRole('button', { name: 'Choose Statistics panel function' }).click();
    await page.getByRole('menuitemradio', { name: 'Comments' }).click();
    await page.getByLabel('New thread comment').fill('Keep this opening.');
    const created = page.waitForResponse(
      (response) =>
        response.url().endsWith(`/screenplays/${screenplayId}/comment-threads`) &&
        response.request().method() === 'POST',
    );
    await page.getByRole('button', { name: 'Start thread' }).click();
    expect((await created).status()).toBe(201);
    await expect(page.getByRole('button', { name: /Anchored range/u })).toContainText('FADE IN:');

    await typeAtDocumentStart(peer, 'BOB ABOVE');
    await expectEditorText(page, 'BOB ABOVE');
    await expect(page.getByRole('button', { name: /Anchored range/u })).toContainText('FADE IN:');
    await expect(page.getByText('Detached thread')).toHaveCount(0);

    await expect
      .poll(async () => {
        const response = await page.request.get(
          `/api/v1/screenplays/${screenplayId}/export.fountain`,
        );
        return response.text();
      })
      .toContain('BOB ABOVE');
    const exported = await page.request.get(`/api/v1/screenplays/${screenplayId}/export.fountain`);
    const fountain = await exported.text();
    expect(fountain).not.toContain('Keep this opening.');
  } finally {
    await peerContext.close();
  }
});
