import { lazy, Suspense, useCallback, useEffect, useRef, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api, ApiError } from './api';
import { applyAccountPreferences, preferencesFromAccount } from './account-preferences';
import { managementProjectId, screenplayIdFromRoute, workspaceProjectId } from './app-routing';
import { ApplicationMasthead } from './app-shell/ApplicationMasthead';
import type { ProjectSummary } from './app-shell/breakdown-menu';
import { WorkspaceRouteLoadingSkeleton } from './app-shell/WorkspaceRouteLoadingSkeleton';
import { AuthScreen, ResetPasswordScreen } from './auth/AuthScreens';
import { reloadBrowserApplication } from './browser-reload';
import { clearSensitiveRouteToken, takeSensitiveRouteToken } from './sensitive-route-token';
import { indexedDbScreenplayRecoveryStore } from './screenplays/screenplay-recovery-store';
import {
  purgeScreenplayRecoveryForLogout,
  retryPendingScreenplayRecoveryCleanup,
} from './screenplays/screenplay-recovery-cleanup';
import { applyTheme, initialTheme, type ThemeId } from './themes';
import { ConfirmationDialog } from './components/ConfirmationDialog';
import { canManageProject } from './projects/access';
import type { SectionId } from './project-management/types';
import type { ManagedProject } from './project-management/types';
import { useProjectDetailsController } from './project-management/useProjectDetailsController';
import { WorkspaceLoadingSkeleton } from './workspace/WorkspaceLoadingSkeleton';
import styles from './App.styles';

const InvitationScreen = lazy(() =>
  import('./InvitationScreen').then((module) => ({ default: module.InvitationScreen })),
);
const ProjectSetupScreen = lazy(() =>
  import('./project-setup/ProjectSetupScreen').then((module) => ({
    default: module.ProjectSetupScreen,
  })),
);
const DashboardShell = lazy(() =>
  import('./app-shell/DashboardShell').then((module) => ({ default: module.DashboardShell })),
);
const ScreenplayEditorScreen = lazy(() =>
  import('./screenplays/ScreenplayEditorScreen').then((module) => ({
    default: module.ScreenplayEditorScreen,
  })),
);
const Workspace = lazy(() =>
  import('./Workspace').then((module) => ({ default: module.Workspace })),
);

const initialSensitiveRouteToken = takeSensitiveRouteToken(window.location, window.history);

interface User {
  id: string;
  email: string;
  displayName: string;
  theme: string;
  fontSize: string;
  motionPreference: string;
  pdfAppearance: string;
}

function CodaLoadingFallback() {
  return <div className={styles.loading}>Loading Coda…</div>;
}

function SensitiveAuthRoute({
  route,
  token,
  currentUser,
  navigate,
}: {
  route: '/accept-invitation' | '/reset-password';
  token: string;
  currentUser?: User;
  navigate: (path: string) => void;
}) {
  const queryClient = useQueryClient();
  const [showSignIn, setShowSignIn] = useState(false);
  if (route === '/reset-password') {
    return (
      <ResetPasswordScreen
        token={token}
        onReset={() => {
          clearSensitiveRouteToken('/reset-password');
          navigate('/');
        }}
      />
    );
  }
  if (showSignIn) {
    return (
      <AuthScreen
        initialized
        setupTokenRequired={false}
        setupTokenAutoGenerated={false}
        onAuthenticated={() => {
          void queryClient.refetchQueries({ queryKey: ['session'] }).finally(() => {
            setShowSignIn(false);
          });
        }}
      />
    );
  }
  return (
    <Suspense fallback={<CodaLoadingFallback />}>
      <InvitationScreen
        token={token}
        currentUser={currentUser}
        onSignIn={() => setShowSignIn(true)}
        onSwitchAccount={() => {
          void api('/api/v1/auth/logout', { method: 'POST' }).finally(() => {
            queryClient.clear();
            reloadBrowserApplication();
          });
        }}
        onAccepted={(redirect) => {
          clearSensitiveRouteToken('/accept-invitation');
          void queryClient.invalidateQueries({ queryKey: ['session'] });
          navigate(redirect ?? '/');
        }}
      />
    </Suspense>
  );
}

function AuthenticatedRoute({
  route,
  workspaceId,
  screenplayId,
  userId,
  isAdministrator,
  theme,
  isFullscreen,
  navigate,
  chooseTheme,
  toggleFullscreen,
  logout,
  managementModal,
  onManagementSectionChange,
  onCloseManagement,
  onManagementDeleted,
  onProjectCreated,
}: {
  route: string;
  workspaceId?: string;
  screenplayId?: string;
  userId: string;
  isAdministrator: boolean;
  theme: ThemeId;
  isFullscreen: boolean;
  navigate: (path: string) => void;
  chooseTheme: (theme: ThemeId) => void;
  toggleFullscreen: () => void;
  logout: () => void;
  managementModal?: { projectId: string; section: SectionId };
  onManagementSectionChange: (section: SectionId) => void;
  onCloseManagement: () => void;
  onManagementDeleted: () => void;
  onProjectCreated: (projectId: string) => void;
}) {
  if (screenplayId) {
    return (
      <Suspense fallback={<CodaLoadingFallback />}>
        <ScreenplayEditorScreen
          screenplayId={screenplayId}
          onBack={() => navigate('/')}
          onOpenScreenplay={(id) => navigate(`/screenplays/${id}`)}
        />
      </Suspense>
    );
  }
  if (route === '/breakdowns/new') {
    return (
      <Suspense fallback={<CodaLoadingFallback />}>
        <ProjectSetupScreen onCancel={() => navigate('/breakdowns')} onCreated={onProjectCreated} />
      </Suspense>
    );
  }
  if (workspaceId) {
    return (
      <Suspense fallback={<WorkspaceLoadingSkeleton />}>
        <Workspace
          projectId={workspaceId}
          currentUserId={userId}
          onBack={() => navigate('/breakdowns')}
          managementSection={
            managementModal?.projectId === workspaceId ? managementModal.section : undefined
          }
          onManagementSectionChange={onManagementSectionChange}
          onCloseManagement={onCloseManagement}
          onDeleted={onManagementDeleted}
        />
      </Suspense>
    );
  }
  return (
    <Suspense fallback={<CodaLoadingFallback />}>
      <DashboardShell
        route={route}
        isAdministrator={isAdministrator}
        theme={theme}
        isFullscreen={isFullscreen}
        onNavigate={navigate}
        chooseTheme={chooseTheme}
        toggleFullscreen={toggleFullscreen}
        logout={logout}
        onOpenProject={(id) => navigate(`/breakdowns/${id}`)}
        onCreateProject={() => navigate('/breakdowns/new')}
        onOpenScreenplay={(id) => navigate(`/screenplays/${id}`)}
      />
    </Suspense>
  );
}

function AppShellMasthead({
  workspaceId,
  screenplayId,
  isDashboard,
  currentProject,
  projects,
  theme,
  isFullscreen,
  navigate,
  chooseTheme,
  toggleFullscreen,
  logout,
  onOpenManagement,
}: {
  workspaceId?: string;
  screenplayId?: string;
  isDashboard: boolean;
  currentProject?: ProjectSummary;
  projects?: ProjectSummary[];
  theme: ThemeId;
  isFullscreen: boolean;
  navigate: (path: string) => void;
  chooseTheme: (theme: ThemeId) => void;
  toggleFullscreen: () => Promise<void>;
  logout: () => Promise<void>;
  onOpenManagement: (section: SectionId) => void;
}) {
  const [workspaceConfirmation, setWorkspaceConfirmation] = useState<'reset' | 'publish'>();
  const management = useQuery({
    queryKey: ['project-management', workspaceId],
    queryFn: () => api<ManagedProject>(`/api/v1/projects/${workspaceId!}/management`),
    enabled: Boolean(workspaceId),
    retry: false,
  });
  const projectDetails = useProjectDetailsController({
    projectId: workspaceId ?? '',
    project: management.data,
  });
  if (workspaceId) {
    const canManage = currentProject ? canManageProject(currentProject) : false;
    return (
      <>
        <ApplicationMasthead
          context={{
            surface: 'breakdown',
            workspaceId,
            currentProject,
            projects,
            theme,
            isFullscreen,
            navigate,
            chooseTheme,
            toggleFullscreen: () => void toggleFullscreen(),
            logout: () => void logout(),
            openShare: () => onOpenManagement('share'),
            openManage: () => onOpenManagement('details'),
            canManage,
            canEditTitle: canManage && Boolean(management.data),
            onRenameTitle: async (name) => {
              if (!management.data) throw new Error('Breakdown details are still loading.');
              await projectDetails.save.mutateAsync({
                name,
                description: management.data.description ?? '',
              });
            },
            requestResetWorkspace: () => setWorkspaceConfirmation('reset'),
            requestPublishWorkspace: () => setWorkspaceConfirmation('publish'),
          }}
        />
        {workspaceConfirmation && (
          <ConfirmationDialog
            title={
              workspaceConfirmation === 'reset'
                ? 'Reset workspace layout?'
                : 'Publish this layout as the default?'
            }
            description={
              workspaceConfirmation === 'reset' ? (
                <p>
                  This replaces your saved panel arrangement with the workspace default. The current
                  arrangement cannot be recovered.
                </p>
              ) : (
                <p>
                  This replaces the default panel arrangement for workspace members. The previous
                  default cannot be recovered.
                </p>
              )
            }
            confirmLabel={workspaceConfirmation === 'reset' ? 'Reset workspace' : 'Publish default'}
            onCancel={() => setWorkspaceConfirmation(undefined)}
            onConfirm={() => {
              window.dispatchEvent(
                new CustomEvent(
                  workspaceConfirmation === 'reset'
                    ? 'coda:reset-workspace'
                    : 'coda:publish-workspace',
                ),
              );
              setWorkspaceConfirmation(undefined);
            }}
          />
        )}
      </>
    );
  }
  // The dashboard and screenplay editors render their own mastheads.
  if (screenplayId || isDashboard) return null;
  return (
    <ApplicationMasthead
      context={{
        surface: 'setup',
        theme,
        isFullscreen,
        navigate,
        chooseTheme,
        toggleFullscreen: () => void toggleFullscreen(),
        logout: () => void logout(),
      }}
    />
  );
}

export function App() {
  const queryClient = useQueryClient();
  const [route, setRoute] = useState(() => window.location.pathname);
  const [theme, setTheme] = useState<ThemeId>(() => initialTheme());
  const [isFullscreen, setIsFullscreen] = useState(() => Boolean(document.fullscreenElement));
  const [managementModal, setManagementModal] = useState<{
    projectId: string;
    section: SectionId;
  }>();
  const sensitiveRouteTokenRef = useRef(initialSensitiveRouteToken);
  const workspaceId = workspaceProjectId(route);
  const managementId = managementProjectId(route);
  const screenplayId = screenplayIdFromRoute(route);
  const setup = useQuery({
    queryKey: ['setup'],
    queryFn: () =>
      api<{
        initialized: boolean;
        setupTokenRequired: boolean;
        setupTokenAutoGenerated: boolean;
      }>('/api/v1/setup/status'),
  });
  const session = useQuery({
    queryKey: ['session'],
    queryFn: () => api<User>('/api/v1/auth/session'),
    enabled: setup.data?.initialized === true,
    retry: false,
  });
  const projects = useQuery({
    queryKey: ['projects'],
    queryFn: () => api<ProjectSummary[]>('/api/v1/projects'),
    enabled: Boolean(session.data),
  });
  const instanceAccess = useQuery({
    queryKey: ['instance-access'],
    queryFn: () => api<{ isAdministrator: boolean }>('/api/v1/instance/access'),
    enabled: Boolean(session.data),
    retry: false,
  });

  const navigate = useCallback((path: string) => {
    history.pushState({}, '', path);
    sensitiveRouteTokenRef.current = takeSensitiveRouteToken(window.location, window.history);
    setRoute(window.location.pathname);
  }, []);
  const chooseTheme = useCallback(
    (nextTheme: ThemeId) => {
      setTheme(nextTheme);
      applyTheme(nextTheme);
      if (!session.data) return;
      const preferences = preferencesFromAccount(session.data);
      void api('/api/v1/account/preferences', {
        method: 'PATCH',
        body: JSON.stringify({ ...preferences, theme: nextTheme }),
      })
        .then(() => {
          queryClient.setQueryData<User>(['session'], (current) =>
            current ? { ...current, theme: nextTheme } : current,
          );
          void queryClient.invalidateQueries({ queryKey: ['account'] });
        })
        .catch(() => {
          // The applied theme remains a valid in-session preview when persistence is unavailable.
        });
    },
    [queryClient, session.data],
  );
  const toggleFullscreen = useCallback(async () => {
    try {
      if (document.fullscreenElement) {
        await document.exitFullscreen();
        return;
      }
      await document.documentElement.requestFullscreen();
    } catch {
      // Fullscreen can be denied by browser policy; the native F11 shortcut remains available.
    }
  }, []);
  const logout = useCallback(async () => {
    const accountId = session.data?.id;
    let cleanupConfirmed = true;
    try {
      await api('/api/v1/auth/logout', { method: 'POST' });
    } catch {
      // The server may already have invalidated the session. Local teardown and
      // recovery cleanup must still run when the response is interrupted.
    } finally {
      if (accountId) cleanupConfirmed = await purgeScreenplayRecoveryForLogout(accountId);
      queryClient.clear();
      navigate('/');
      if (!cleanupConfirmed) {
        window.alert(
          'Coda could not remove this account’s local screenplay recovery drafts. Clear this site’s browser data before another person uses this profile.',
        );
      }
      reloadBrowserApplication();
    }
  }, [navigate, queryClient, session.data]);

  useEffect(() => {
    void Promise.allSettled([
      retryPendingScreenplayRecoveryCleanup(),
      indexedDbScreenplayRecoveryStore.purgeExpired(),
    ]);
  }, []);

  useEffect(() => {
    const updateRoute = () => {
      sensitiveRouteTokenRef.current = takeSensitiveRouteToken(window.location, window.history);
      setRoute(window.location.pathname);
    };
    window.addEventListener('popstate', updateRoute);
    return () => window.removeEventListener('popstate', updateRoute);
  }, []);
  useEffect(() => {
    const updateFullscreenState = () => setIsFullscreen(Boolean(document.fullscreenElement));
    document.addEventListener('fullscreenchange', updateFullscreenState);
    return () => document.removeEventListener('fullscreenchange', updateFullscreenState);
  }, []);
  useEffect(() => {
    if (!session.data) return;
    const preferences = preferencesFromAccount(session.data);
    applyAccountPreferences(preferences);
    setTheme(preferences.theme);
  }, [session.data]);
  useEffect(() => {
    const syncThemeState = (event: Event) => {
      const nextTheme = (event as CustomEvent<ThemeId>).detail;
      if (nextTheme) setTheme(nextTheme);
    };
    window.addEventListener('coda:theme-change', syncThemeState);
    return () => window.removeEventListener('coda:theme-change', syncThemeState);
  }, []);

  const token = sensitiveRouteTokenRef.current;
  if (route === '/accept-invitation' || route === '/reset-password') {
    return (
      <SensitiveAuthRoute
        route={route}
        token={token}
        currentUser={session.data}
        navigate={navigate}
      />
    );
  }
  if (setup.isLoading || (setup.data?.initialized && session.isLoading)) {
    return workspaceId ? (
      <WorkspaceRouteLoadingSkeleton />
    ) : (
      <div className={styles.loading}>Loading Coda…</div>
    );
  }
  if (setup.error) return <div className={styles.loading}>Coda could not reach its API.</div>;
  if (!setup.data?.initialized || session.error instanceof ApiError) {
    const setupStatus = setup.data ?? {
      initialized: false,
      setupTokenRequired: false,
      setupTokenAutoGenerated: false,
    };
    return (
      <AuthScreen
        initialized={setupStatus.initialized}
        setupTokenRequired={setupStatus.setupTokenRequired}
        setupTokenAutoGenerated={setupStatus.setupTokenAutoGenerated}
        onAuthenticated={() => void queryClient.invalidateQueries({ queryKey: ['session'] })}
        onRestored={() => {
          void queryClient.invalidateQueries({ queryKey: ['setup'] });
          void queryClient.invalidateQueries({ queryKey: ['session'] });
        }}
      />
    );
  }

  const activeProjectId = workspaceId ?? managementId;
  const currentProject = projects.data?.find((project) => project.id === activeProjectId);
  const isDashboard = !workspaceId && !screenplayId && route !== '/breakdowns/new';
  return (
    <div
      className={`${styles.shell} ${
        workspaceId || route === '/breakdowns/new' ? styles.editorShell : ''
      }`}
    >
      <AppShellMasthead
        workspaceId={workspaceId}
        screenplayId={screenplayId}
        isDashboard={isDashboard}
        currentProject={currentProject}
        projects={projects.data}
        theme={theme}
        isFullscreen={isFullscreen}
        navigate={navigate}
        chooseTheme={chooseTheme}
        toggleFullscreen={toggleFullscreen}
        logout={logout}
        onOpenManagement={(section) => {
          if (workspaceId) setManagementModal({ projectId: workspaceId, section });
        }}
      />
      <AuthenticatedRoute
        route={route}
        workspaceId={workspaceId}
        screenplayId={screenplayId}
        userId={session.data!.id}
        isAdministrator={instanceAccess.data?.isAdministrator === true}
        theme={theme}
        isFullscreen={isFullscreen}
        navigate={navigate}
        chooseTheme={chooseTheme}
        toggleFullscreen={() => void toggleFullscreen()}
        logout={() => void logout()}
        managementModal={managementModal}
        onManagementSectionChange={(section) =>
          setManagementModal((current) => (current ? { ...current, section } : current))
        }
        onCloseManagement={() => setManagementModal(undefined)}
        onManagementDeleted={() => {
          setManagementModal(undefined);
          navigate('/breakdowns');
        }}
        onProjectCreated={(id) => {
          void queryClient
            .invalidateQueries({ queryKey: ['projects'] })
            .then(() => navigate(`/breakdowns/${id}`));
        }}
      />
    </div>
  );
}
