export const messages = {
  brand: 'Coda',
  strapline: 'Unfolding the blueprint of your story.',
  setupTitle: 'Set up this Coda instance',
  setupTokenLabel: 'Instance setup token',
  setupTokenAutoGeneratedHint:
    'Coda generated a one-time setup token at startup. Copy it from the container logs (look for the “CODA SETUP TOKEN” banner) and paste it here.',
  loginTitle: 'Welcome back',
  projects: 'Breakdowns',
  newProject: 'New breakdown',
  noProjects: 'Create a breakdown to begin analyzing a source document.',
  emptyItems: 'No items at this level yet.',
  source: 'Source',
  activity: 'Activity',
  collaborators: 'Collaborators',
} as const;
