export const messages = {
  brand: 'Coda',
  strapline: 'Unfolding the blueprint of your story.',
  setupTitle: 'Set up this Coda instance',
  setupTokenLabel: 'Instance setup token',
  setupTokenAutoGeneratedHint:
    'Coda generated a one-time setup token at startup. Copy it from the container logs (look for the “CODA SETUP TOKEN” banner) and paste it here.',
  setupRestoreTitle: 'Restore from a backup',
  setupRestoreIntro:
    'Restore a signed backup archive into this fresh instance instead of creating a new owner account. The archive must have been produced by an instance sharing this deployment’s CONFIG_ENCRYPTION_KEY.',
  setupRestoreSwitch: 'Restore from a backup instead',
  setupRestoreBack: 'Create an owner account instead',
  setupRestoreFileLabel: 'Backup archive',
  setupRestoreSubmit: 'Restore this instance',
  setupRestoreSuccess:
    'Restore complete. This instance now holds the backed-up data. Continue to sign in with an account from the restored instance.',
  loginTitle: 'Welcome back',
  projects: 'Breakdowns',
  newProject: 'New breakdown',
  noProjects: 'Create a breakdown to begin analyzing a source document.',
  emptyItems: 'No items at this level yet.',
  source: 'Source',
  activity: 'Activity',
  collaborators: 'Collaborators',
} as const;
