import { describe, expect, it } from 'vitest';

/**
 * Proves the desktop runtime profile end-to-end against a REAL API boot (RUNTIME_PROFILE=desktop)
 * backed by a disposable Postgres — no Electron required. Opt-in: it runs only when the orchestration
 * has booted such an instance and exported its URL, so the standard `pnpm test:integration` run
 * (which drives the default server-profile compose stack) is unaffected.
 *
 * Orchestration (see the PR verification notes for the exact commands):
 *   1. start a throwaway Postgres and `prisma migrate deploy` against it;
 *   2. boot the built API with RUNTIME_PROFILE=desktop against it (NODE_ENV=production, which on the
 *      server profile would REQUIRE a setup token — so a bypass here is meaningful);
 *   3. run this file with CODA_DESKTOP_API_URL pointing at that instance.
 *
 * The disabled-update-poller and single-process-scheduler toggles are proven at the unit level
 * (release-checker.desktop.test.ts, advisory-lock.desktop.test.ts) and observed in the same live
 * boot's database state (release_check_state empty; scheduler.heartbeat recorded a startup run).
 */
const apiUrl = process.env.CODA_DESKTOP_API_URL;

interface SetupStatus {
  data: {
    initialized: boolean;
    setupTokenRequired: boolean;
    setupTokenAutoGenerated: boolean;
  };
}

describe.runIf(apiUrl)('Desktop runtime profile (real boot against disposable Postgres)', () => {
  it('auto-initializes a local owner and never runs the setup-token ceremony', async () => {
    const response = await fetch(`${apiUrl}/api/v1/setup/status`);
    expect(response.status).toBe(200);
    const status = (await response.json()) as SetupStatus;

    // The instance is already initialized on first boot — no operator setup POST ever happened.
    expect(status.data.initialized).toBe(true);
    // No token ceremony: nothing is required and nothing was auto-generated, even under
    // NODE_ENV=production where the server profile would demand a setup token.
    expect(status.data.setupTokenRequired).toBe(false);
    expect(status.data.setupTokenAutoGenerated).toBe(false);
  });

  it('rejects a would-be second owner (the single local owner already exists)', async () => {
    // With the owner auto-provisioned, the public setup endpoint can no longer create one:
    // proof the auto-initialization actually persisted an owner + instance settings.
    const response = await fetch(`${apiUrl}/api/v1/setup/owner`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({
        displayName: 'Second Owner',
        email: 'second@example.com',
        password: 'Meridian-Backdrop-Owner-2026',
      }),
    });
    expect(response.status).toBe(409);
  });
});
