// @vitest-environment jsdom

import '@testing-library/jest-dom/vitest';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import type { ReactElement } from 'react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { AuthScreen } from './AuthScreens';
import { messages } from '../messages';
import * as setupRestore from './setup-restore';

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

function renderWithClient(node: ReactElement) {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  return render(<QueryClientProvider client={client}>{node}</QueryClientProvider>);
}

describe('AuthScreen restore mode', () => {
  it('offers a restore switch only during first-run setup', () => {
    const { rerender } = renderWithClient(
      <AuthScreen initialized={false} setupTokenRequired={false} onAuthenticated={() => {}} />,
    );
    expect(screen.getByRole('button', { name: messages.setupRestoreSwitch })).toBeInTheDocument();

    rerender(
      <QueryClientProvider client={new QueryClient()}>
        <AuthScreen initialized setupTokenRequired={false} onAuthenticated={() => {}} />
      </QueryClientProvider>,
    );
    expect(
      screen.queryByRole('button', { name: messages.setupRestoreSwitch }),
    ).not.toBeInTheDocument();
  });

  it('toggles into the restore panel and back to owner creation', () => {
    renderWithClient(
      <AuthScreen initialized={false} setupTokenRequired={false} onAuthenticated={() => {}} />,
    );
    fireEvent.click(screen.getByRole('button', { name: messages.setupRestoreSwitch }));
    expect(screen.getByRole('heading', { name: messages.setupRestoreTitle })).toBeInTheDocument();

    fireEvent.click(screen.getByRole('button', { name: messages.setupRestoreBack }));
    expect(screen.getByRole('button', { name: 'Create owner account' })).toBeInTheDocument();
  });

  it('validates that an archive is chosen before restoring', () => {
    const stream = vi.spyOn(setupRestore, 'streamSetupRestore');
    renderWithClient(
      <AuthScreen initialized={false} setupTokenRequired={false} onAuthenticated={() => {}} />,
    );
    fireEvent.click(screen.getByRole('button', { name: messages.setupRestoreSwitch }));
    fireEvent.click(screen.getByRole('button', { name: messages.setupRestoreSubmit }));
    expect(screen.getByText('Choose a backup archive to restore.')).toBeInTheDocument();
    expect(stream).not.toHaveBeenCalled();
  });

  it('runs the restore and surfaces onRestored on completion', async () => {
    const onRestored = vi.fn();
    vi.spyOn(setupRestore, 'streamSetupRestore').mockResolvedValue({ appVersion: '0.0.4' });
    renderWithClient(
      <AuthScreen
        initialized={false}
        setupTokenRequired={false}
        onAuthenticated={() => {}}
        onRestored={onRestored}
      />,
    );
    fireEvent.click(screen.getByRole('button', { name: messages.setupRestoreSwitch }));
    const file = new File([Buffer.from('archive')], 'coda.codabk', {
      type: 'application/octet-stream',
    });
    const input = document.querySelector('input[type="file"]') as HTMLInputElement;
    fireEvent.change(input, { target: { files: [file] } });
    fireEvent.click(screen.getByRole('button', { name: messages.setupRestoreSubmit }));

    await waitFor(() => expect(screen.getByText(messages.setupRestoreSuccess)).toBeInTheDocument());
    fireEvent.click(screen.getByRole('button', { name: 'Continue to sign in' }));
    expect(onRestored).toHaveBeenCalledTimes(1);
  });

  it('shows a terminal error when the restore fails', async () => {
    vi.spyOn(setupRestore, 'streamSetupRestore').mockRejectedValue(
      new Error('Backup manifest signature is invalid'),
    );
    renderWithClient(
      <AuthScreen
        initialized={false}
        setupTokenRequired
        setupTokenAutoGenerated
        onAuthenticated={() => {}}
      />,
    );
    fireEvent.click(screen.getByRole('button', { name: messages.setupRestoreSwitch }));
    fireEvent.change(document.querySelector('input[type="password"]') as HTMLInputElement, {
      target: { value: 'token' },
    });
    const file = new File([Buffer.from('archive')], 'coda.codabk');
    fireEvent.change(document.querySelector('input[type="file"]') as HTMLInputElement, {
      target: { files: [file] },
    });
    fireEvent.click(screen.getByRole('button', { name: messages.setupRestoreSubmit }));

    await waitFor(() =>
      expect(screen.getByText('Backup manifest signature is invalid')).toBeInTheDocument(),
    );
  });
});
