import { useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { PASSWORD_MIN_LENGTH } from '@coda/contracts';
import { api } from '../api';
import { messages } from '../messages';
import styles from '../App.styles';
import { streamSetupRestore, type RestoreProgress } from './setup-restore';

interface AuthFields {
  displayName: string;
  email: string;
  password: string;
  setupToken?: string;
}

function restorePhaseLabel(progress: RestoreProgress): string {
  switch (progress.phase) {
    case 'verify-archive':
      return 'Verifying the archive signature…';
    case 'restore-database':
      return 'Restoring the database…';
    case 'restore-object':
      return progress.total
        ? `Restoring stored objects (${progress.index ?? 0}/${progress.total})…`
        : 'Restoring stored objects…';
    default:
      return 'Restoring…';
  }
}

function SetupRestorePanel({
  setupTokenRequired,
  setupTokenAutoGenerated,
  onBack,
  onRestored,
}: {
  setupTokenRequired: boolean;
  setupTokenAutoGenerated: boolean;
  onBack: () => void;
  onRestored?: () => void;
}) {
  const [file, setFile] = useState<File | null>(null);
  const [setupToken, setSetupToken] = useState('');
  const [progress, setProgress] = useState<RestoreProgress | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [state, setState] = useState<'idle' | 'running' | 'done'>('idle');

  const submit = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!file) {
      setError('Choose a backup archive to restore.');
      return;
    }
    setError(null);
    setState('running');
    setProgress({ event: 'progress', phase: 'verify-archive' });
    try {
      await streamSetupRestore(file, setupTokenRequired ? setupToken : undefined, setProgress);
      setState('done');
    } catch (restoreError) {
      setError(restoreError instanceof Error ? restoreError.message : 'The restore failed.');
      setState('idle');
    }
  };

  if (state === 'done') {
    return (
      <div className={styles.authPage}>
        <AuthBrand />
        <main className={styles.authPanel}>
          <div className={styles.card}>
            <h2>{messages.setupRestoreTitle}</h2>
            <p className={styles.fieldHint} role="status">
              {messages.setupRestoreSuccess}
            </p>
            <button type="button" className={styles.primary} onClick={() => onRestored?.()}>
              Continue to sign in
            </button>
          </div>
        </main>
      </div>
    );
  }

  const running = state === 'running';
  return (
    <div className={styles.authPage}>
      <AuthBrand />
      <main className={styles.authPanel}>
        <div className={styles.card}>
          <h2>{messages.setupRestoreTitle}</h2>
          <p className={styles.fieldHint}>{messages.setupRestoreIntro}</p>
          <form className={styles.form} onSubmit={submit}>
            {setupTokenRequired && (
              <>
                <label className={styles.field}>
                  <span>{messages.setupTokenLabel}</span>
                  <input
                    type="password"
                    autoComplete="off"
                    value={setupToken}
                    onChange={(event) => setSetupToken(event.target.value)}
                    required
                  />
                </label>
                {setupTokenAutoGenerated && (
                  <p className={styles.fieldHint}>{messages.setupTokenAutoGeneratedHint}</p>
                )}
              </>
            )}
            <label className={styles.field}>
              <span>{messages.setupRestoreFileLabel}</span>
              <input
                type="file"
                accept=".codabk,application/octet-stream"
                onChange={(event) => setFile(event.target.files?.[0] ?? null)}
              />
            </label>
            {error && <div className={styles.error}>{error}</div>}
            {running && progress && (
              <p className={styles.fieldHint} role="status">
                {restorePhaseLabel(progress)}
              </p>
            )}
            <button className={styles.primary} disabled={running}>
              {running ? 'Restoring…' : messages.setupRestoreSubmit}
            </button>
            <button type="button" className={styles.secondary} onClick={onBack} disabled={running}>
              {messages.setupRestoreBack}
            </button>
          </form>
        </div>
      </main>
    </div>
  );
}

function AuthBrand() {
  return (
    <section className={styles.authIntro} aria-labelledby="auth-brand">
      <h1 id="auth-brand">
        <span className={styles.authLogoMark} aria-hidden="true" />
        <span className={styles.visuallyHidden}>{messages.brand}</span>
      </h1>
      <p>{messages.strapline}</p>
    </section>
  );
}

export function ResetPasswordScreen({ token, onReset }: { token: string; onReset: () => void }) {
  const { register, handleSubmit } = useForm<{ password: string }>();
  const reset = useMutation({
    mutationFn: ({ password }: { password: string }) =>
      api<{ reset: true }>('/api/v1/auth/reset-password', {
        method: 'POST',
        body: JSON.stringify({ token, password }),
      }),
    onSuccess: onReset,
  });

  return (
    <div className={styles.authPage}>
      <AuthBrand />
      <main className={styles.authPanel}>
        <div className={styles.card}>
          <h2>Choose a new password</h2>
          <form className={styles.form} onSubmit={handleSubmit((values) => reset.mutate(values))}>
            <label className={styles.field}>
              <span>New password</span>
              <input
                type="password"
                autoComplete="new-password"
                minLength={PASSWORD_MIN_LENGTH}
                {...register('password', { required: true })}
              />
            </label>
            <p className={styles.fieldHint}>
              Use at least {PASSWORD_MIN_LENGTH} characters. Avoid common or previously leaked
              passwords.
            </p>
            {reset.error && <div className={styles.error}>{reset.error.message}</div>}
            <button className={styles.primary} disabled={reset.isPending}>
              {reset.isPending ? 'Updating…' : 'Update password'}
            </button>
          </form>
        </div>
      </main>
    </div>
  );
}

export function AuthScreen({
  initialized,
  setupTokenRequired,
  setupTokenAutoGenerated = false,
  onAuthenticated,
  onRestored,
}: {
  initialized: boolean;
  setupTokenRequired: boolean;
  setupTokenAutoGenerated?: boolean;
  onAuthenticated: () => void;
  onRestored?: () => void;
}) {
  const [mode, setMode] = useState<'create' | 'restore'>('create');
  const { register, handleSubmit } = useForm<AuthFields>();
  const mutation = useMutation({
    mutationFn: (values: AuthFields) => {
      const { setupToken, ...body } = values;
      return api(initialized ? '/api/v1/auth/login' : '/api/v1/setup/owner', {
        method: 'POST',
        headers: setupToken ? { 'x-coda-setup-token': setupToken } : undefined,
        body: JSON.stringify(body),
      });
    },
    onSuccess: onAuthenticated,
  });
  if (!initialized && mode === 'restore') {
    return (
      <SetupRestorePanel
        setupTokenRequired={setupTokenRequired}
        setupTokenAutoGenerated={setupTokenAutoGenerated}
        onBack={() => setMode('create')}
        onRestored={onRestored}
      />
    );
  }
  return (
    <div className={styles.authPage}>
      <AuthBrand />
      <main className={styles.authPanel}>
        <div className={`${styles.card} ${initialized ? styles.loginCard : ''}`}>
          <h2 className={initialized ? styles.visuallyHidden : undefined}>
            {initialized ? messages.loginTitle : messages.setupTitle}
          </h2>
          <form
            className={styles.form}
            onSubmit={handleSubmit((values) => mutation.mutate(values))}
          >
            {!initialized && (
              <>
                <label className={styles.field}>
                  <span>Display name</span>
                  <input autoComplete="name" {...register('displayName', { required: true })} />
                </label>
                {setupTokenRequired && (
                  <>
                    <label className={styles.field}>
                      <span>{messages.setupTokenLabel}</span>
                      <input
                        type="password"
                        autoComplete="off"
                        {...register('setupToken', { required: true })}
                      />
                    </label>
                    {setupTokenAutoGenerated && (
                      <p className={styles.fieldHint}>{messages.setupTokenAutoGeneratedHint}</p>
                    )}
                  </>
                )}
              </>
            )}
            <label className={styles.field}>
              <span>Email</span>
              <input
                type="email"
                autoComplete="email"
                placeholder={initialized ? 'you@email.com' : undefined}
                {...register('email', { required: true })}
              />
            </label>
            <label className={styles.field}>
              <span>Password</span>
              <input
                type="password"
                autoComplete={initialized ? 'current-password' : 'new-password'}
                minLength={initialized ? undefined : PASSWORD_MIN_LENGTH}
                placeholder={initialized ? 'password' : undefined}
                {...register('password', { required: true })}
              />
            </label>
            {!initialized && (
              <p className={styles.fieldHint}>
                Use at least {PASSWORD_MIN_LENGTH} characters. Avoid common or previously leaked
                passwords.
              </p>
            )}
            {mutation.error && <div className={styles.error}>{mutation.error.message}</div>}
            <button className={styles.primary} disabled={mutation.isPending}>
              {mutation.isPending ? 'Working…' : initialized ? 'Log in' : 'Create owner account'}
            </button>
            {!initialized && (
              <button
                type="button"
                className={styles.secondary}
                onClick={() => setMode('restore')}
                disabled={mutation.isPending}
              >
                {messages.setupRestoreSwitch}
              </button>
            )}
          </form>
        </div>
      </main>
    </div>
  );
}
